services:
  ui:
    build: .
    ports:
      - "3030:5173" # Make Vite frontend accessible on localhost port
    depends_on:
      - api # ui service will wait for api to be ready
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app/client
          ignore:
            - node_modules/
        - action: rebuild # packages can be arch dependent -> need to rebuild if they change. See https://docs.docker.com/compose/how-tos/file-watch/
          path: package.json

  api:
    build: ./db
    ports:
      - "5001:5000" # Map a host port to container api port
    develop:
      watch:
        - action: sync
          path: ./db
          target: /app/db
        - action: rebuild # packages can be arch dependent -> need to rebuild if they change. See https://docs.docker.com/compose/how-tos/file-watch/
          path: requirements.txt
